# Generated by Django 3.0.6 on 2020-06-20 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instruction', models.CharField(max_length=300)),
                ('image_height', models.IntegerField()),
                ('image_width', models.IntegerField()),
                ('thumbnail', models.ImageField(default='thumbnail_images/default.jpg', height_field='image_height', upload_to='thumbnail_images', width_field='image_width')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportMsg', models.CharField(max_length=300)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Issue')),
            ],
        ),
    ]
