# Generated by Django 3.0.6 on 2020-05-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instruction', models.CharField(max_length=300)),
                ('reportStatus', models.BooleanField(default=False)),
                ('reportMessage', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Issue')),
            ],
        ),
    ]
