# Generated by Django 3.0.6 on 2020-05-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagecoord_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='thumbnail',
            field=models.ImageField(default='recipe_thumbnails/default.png', upload_to='recipe_thumbnails'),
        ),
    ]
