# Generated by Django 3.0.6 on 2020-05-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200531_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='reportMessage',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='reportStatus',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportMsg', models.CharField(max_length=300)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Issue')),
            ],
        ),
    ]
